FROM fedora-toolbox:36

LABEL com.github.containers.toolbox="true" \
    com.github.debarshiray.toolbox="true"

ARG LANGPACK=en
ARG GLIBC_LANGPACK=en
ARG JAVA_VERSION=17

# Configure vscode repository
RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc

COPY vscode.repo /etc/yum.repos.d/vscode.repo

# Install rpmfusion repository
RUN dnf update -y \
    && dnf install -y \
    https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# Install packages
RUN dnf install -y \
    langpacks-${LANGPACK} \
    glibc-langpack-${GLIBC_LANGPACK} \
    zsh \
    sqlite \
    vim \
    xclip \
    mesa-dri-drivers \
    code \
    community-mysql \
    python-unversioned-command \
    python3-pip \
    php-cli \
    java-${JAVA_VERSION}-openjdk-headless \
    java-${JAVA_VERSION}-openjdk-devel \
    make \
    automake \
    gcc \
    gcc-c++ \
    kernel-devel \
    adwaita-gtk2-theme \
    gnome-themes-extra \
    google-noto-emoji-fonts \
    p7zip \
    p7zip-plugins \
    unrar

# Clean packages
RUN dnf clean all

CMD /usr/bin/zsh
