FROM fedora-toolbox:37

LABEL com.github.containers.toolbox="true" \
    com.github.debarshiray.toolbox="true"

ARG JAVA_VERSION=17

# Configure vscode repository
RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc

COPY vscode.repo /etc/yum.repos.d/vscode.repo

# Install rpmfusion repository
RUN dnf update -y \
    && dnf install -y \
    https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# Install compilers
RUN dnf groupinstall -y 'C Development Tools and Libraries'

# Install packages
RUN dnf install -y \
    zsh \
    sqlite \
    flatpak \
    vim \
    xclip \
    mesa-dri-drivers \
    code \
    community-mysql \
    python-unversioned-command \
    python3-pip \
    php-cli \
    java-${JAVA_VERSION}-openjdk-headless \
    java-${JAVA_VERSION}-openjdk-devel \
    adwaita-gtk2-theme \
    gnome-themes-extra \
    google-noto-emoji-fonts \
    p7zip \
    p7zip-plugins \
    unrar \
    exa \
    bat

# Clean packages
RUN dnf clean all

