FROM localhost/base

LABEL com.github.containers.toolbox="true" \
    com.github.debarshiray.toolbox="true"

ARG JAVA_VERSION=17

RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc

COPY vscode.repo /etc/yum.repos.d

RUN dnf update -y \
    && dnf install -y \
    https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

RUN dnf install -y \
    mesa-dri-drivers \
    code \
    community-mysql \
    python-unversioned-command \
    python3-pip \
    php-cli \
    java-${JAVA_VERSION}-openjdk-headless \
    java-${JAVA_VERSION}-openjdk-devel \
    make \
    automake \
    gcc \
    gcc-c++ \
    kernel-devel \
    adwaita-gtk2-theme \
    gnome-themes-extra \
    google-noto-emoji-fonts \
    p7zip \
    p7zip-plugins \
    unrar

RUN dnf clean all

CMD /usr/bin/zsh
