FROM archlinux

LABEL com.github.containers.toolbox="true" \
  com.github.debarshiray.toolbox="true"

ARG USER
ARG JAVA_VERSION=17
ARG LANGUAGE=en_US.UTF-8
ARG YAY_LINK=https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=yay

RUN sed -i 's/^\(NoExtract\)/#\1/g' /etc/pacman.conf

RUN pacman --noconfirm -Syu \
  && pacman --noconfirm -S \
  # Reinstall glibc to force install locate package
  glibc \
  base-devel \
  openssh \
  zsh \
  sudo \
  git \
  wget \
  xclip \
  vim \
  php \
  python \
  python-pip \
  jdk${JAVA_VERSION}-openjdk \
  # To get mysql and mysqldump commands
  mariadb-clients \
  # For theme integration with host
  gnome-themes-extra \
  adwaita-icon-theme \
  libadwaita \
  # For xdg-open integration with flatpak apps on host
  flatpak \
  flatpak-xdg-utils

# Configure location
RUN sed -i "s/^#\(${LANGUAGE}\)/\1/" /etc/locale.gen \
  && echo LANG=${LANGUAGE} | tee /etc/locale.conf \
  && locale-gen

# Create temporary user to use makepkg
RUN useradd -m -s /bin/bash -d /build build \
  && echo "build ALL=NOPASSWD: ALL" >> /etc/sudoers

WORKDIR /tmp

# Install yay helper
RUN wget -c --timeout=5 ${YAY_LINK} -O PKGBUILD \
  && sudo -u build makepkg --noconfirm -cis \
  && rm -f PKGBUILD

RUN sudo -u build \
  yay --noconfirm -S \
  visual-studio-code-bin

RUN userdel -r build \
  && sudo sed -i '/^build/d' /etc/sudoers \
  && pacman --noconfirm -Scc

# Configure sudo for host user
RUN echo -en "Defaults !fqdn\n\"${USER}\" ALL = (root) NOPASSWD:ALL\n" \
  | tee /etc/sudoers.d/sudoers

CMD /usr/bin/zsh
