ARG FEDORA_VERSION=latest
FROM registry.fedoraproject.org/fedora-toolbox:${FEDORA_VERSION}

LABEL com.github.containers.toolbox="true" \
    com.github.debarshiray.toolbox="true"

ARG LANGPACK=en
ARG GLIBC_LANGPACK=en

RUN dnf update -y \
    && dnf install -y \
    langpacks-${LANGPACK} \
    glibc-langpack-${GLIBC_LANGPACK} \
    zsh \
    sqlite \
    vim \
    xclip

RUN dnf clean all

CMD /usr/bin/zsh
